### ISSUE TITLE
Prediction score issue

### ISSUE THREAD

**Issue by woudsma** [uwdata/gestrec#3]
The prediction score isn't normalized between 0 and 1, instead i get scores like 2.4 or 22 in some cases. How can i detect whether a prediction is good enough to be counted as a gesture?
`prediction.score > 0.9 ? 'gesture' : 'no gesture'` doesn't do the trick

**Comment by jheer** [comment]
That is correct: scores produced by the Protractor algorithm are not normalized. We've found `2.5` to be a good threshold value. (For example, see the [web application in the gh-pages branch](https://github.com/uwdata/gestrec/blob/gh-pages/index.html).)
